management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true